build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6c7cbab
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6c7cbab
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6c7cbab
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev