name: "Twingate Connector"
description: "Connector for Twingate"
version: "1.1.1"
slug: "twingate-connector"
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  access_token: ""
  refresh_token: ""
  network: ""
  connector_log_level: "info"
schema:
  access_token: str
  refresh_token: str
  network: str
  connector_log_level: list(info|debug)
ingress: true
image: "ghcr.io/twingate-community/{arch}-twingate-connector"
codenotary: "andrewb@twingate.com"
